easy_admin:
    entities:
        Utilisateur:
            class: App\Entity\Utilisateur
            controller: App\Controller\UtilisateurController
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User
#        - App\Entity\Utilisateur
        Role:
            class: App\Entity\Role
